### PR TITLE
Setup server using Vagrant

### PR DESCRIPTION
**Pull request by sverhoeven**
Also uses https://github.com/MonolithProjects/ansible-github_actions_runner role to setup runner

### CODE REVIEW

**Comment by fdiblen** [comment]
I knew this would come from you :) Thank you @sverhoeven

**Comment by sverhoeven** [comment]
1. Handled added note
2. Yeah, the ansible role used here requires a GH Personal Access Token instead of a GH Action runner token.
4. Which version of ansible are you using? I am using 2.9.9 which parses ./ansible.cfg to find inventory file.
4. Something is up with you firewall, DNS seems to work but http requests don't

**Comment by jspaaks** [comment]
All good! 
:racehorse:

**Comment by jspaaks** [comment]
Since we want to transfer this repo to the ci-for-science org, I merged it already.

**Pull request merged**
